# Generated by Django 2.2 on 2021-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('moviename', models.CharField(max_length=60)),
                ('hero', models.CharField(max_length=60)),
                ('heroine', models.CharField(max_length=60)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
