# Generated by Django 2.2 on 2021-02-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rdate',
            field=models.IntegerField(),
        ),
    ]
